// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: restaurant.proto
// Protobuf Java Version: 4.28.2

package me.grpc.restaurant;

public interface CategoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CategoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Category category = 1;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <code>.Category category = 1;</code>
   * @return The category.
   */
  me.grpc.restaurant.Category getCategory();
}
