// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: restaurant.proto
// Protobuf Java Version: 4.28.2

package me.grpc.restaurant;

/**
 * Protobuf type {@code Restaurant}
 */
public final class Restaurant extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Restaurant)
    RestaurantOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Restaurant.class.getName());
  }
  // Use Restaurant.newBuilder() to construct.
  private Restaurant(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Restaurant() {
    name_ = "";
    location_ = "";
    contactNumber_ = "";
    menu_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.grpc.restaurant.RestaurantOuterClass.internal_static_Restaurant_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.grpc.restaurant.RestaurantOuterClass.internal_static_Restaurant_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.grpc.restaurant.Restaurant.class, me.grpc.restaurant.Restaurant.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object location_ = "";
  /**
   * <code>string location = 2;</code>
   * @return The location.
   */
  @java.lang.Override
  public java.lang.String getLocation() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location_ = s;
      return s;
    }
  }
  /**
   * <code>string location = 2;</code>
   * @return The bytes for location.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocationBytes() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTACT_NUMBER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contactNumber_ = "";
  /**
   * <code>string contact_number = 3;</code>
   * @return The contactNumber.
   */
  @java.lang.Override
  public java.lang.String getContactNumber() {
    java.lang.Object ref = contactNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contactNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string contact_number = 3;</code>
   * @return The bytes for contactNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContactNumberBytes() {
    java.lang.Object ref = contactNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contactNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MENU_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<me.grpc.restaurant.MenuItem> menu_;
  /**
   * <code>repeated .MenuItem menu = 4;</code>
   */
  @java.lang.Override
  public java.util.List<me.grpc.restaurant.MenuItem> getMenuList() {
    return menu_;
  }
  /**
   * <code>repeated .MenuItem menu = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends me.grpc.restaurant.MenuItemOrBuilder> 
      getMenuOrBuilderList() {
    return menu_;
  }
  /**
   * <code>repeated .MenuItem menu = 4;</code>
   */
  @java.lang.Override
  public int getMenuCount() {
    return menu_.size();
  }
  /**
   * <code>repeated .MenuItem menu = 4;</code>
   */
  @java.lang.Override
  public me.grpc.restaurant.MenuItem getMenu(int index) {
    return menu_.get(index);
  }
  /**
   * <code>repeated .MenuItem menu = 4;</code>
   */
  @java.lang.Override
  public me.grpc.restaurant.MenuItemOrBuilder getMenuOrBuilder(
      int index) {
    return menu_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, location_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contactNumber_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, contactNumber_);
    }
    for (int i = 0; i < menu_.size(); i++) {
      output.writeMessage(4, menu_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, location_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contactNumber_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, contactNumber_);
    }
    for (int i = 0; i < menu_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, menu_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.grpc.restaurant.Restaurant)) {
      return super.equals(obj);
    }
    me.grpc.restaurant.Restaurant other = (me.grpc.restaurant.Restaurant) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getLocation()
        .equals(other.getLocation())) return false;
    if (!getContactNumber()
        .equals(other.getContactNumber())) return false;
    if (!getMenuList()
        .equals(other.getMenuList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation().hashCode();
    hash = (37 * hash) + CONTACT_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getContactNumber().hashCode();
    if (getMenuCount() > 0) {
      hash = (37 * hash) + MENU_FIELD_NUMBER;
      hash = (53 * hash) + getMenuList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.grpc.restaurant.Restaurant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static me.grpc.restaurant.Restaurant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static me.grpc.restaurant.Restaurant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static me.grpc.restaurant.Restaurant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.grpc.restaurant.Restaurant prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Restaurant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Restaurant)
      me.grpc.restaurant.RestaurantOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.grpc.restaurant.RestaurantOuterClass.internal_static_Restaurant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.grpc.restaurant.RestaurantOuterClass.internal_static_Restaurant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.grpc.restaurant.Restaurant.class, me.grpc.restaurant.Restaurant.Builder.class);
    }

    // Construct using me.grpc.restaurant.Restaurant.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      location_ = "";
      contactNumber_ = "";
      if (menuBuilder_ == null) {
        menu_ = java.util.Collections.emptyList();
      } else {
        menu_ = null;
        menuBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.grpc.restaurant.RestaurantOuterClass.internal_static_Restaurant_descriptor;
    }

    @java.lang.Override
    public me.grpc.restaurant.Restaurant getDefaultInstanceForType() {
      return me.grpc.restaurant.Restaurant.getDefaultInstance();
    }

    @java.lang.Override
    public me.grpc.restaurant.Restaurant build() {
      me.grpc.restaurant.Restaurant result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.grpc.restaurant.Restaurant buildPartial() {
      me.grpc.restaurant.Restaurant result = new me.grpc.restaurant.Restaurant(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(me.grpc.restaurant.Restaurant result) {
      if (menuBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          menu_ = java.util.Collections.unmodifiableList(menu_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.menu_ = menu_;
      } else {
        result.menu_ = menuBuilder_.build();
      }
    }

    private void buildPartial0(me.grpc.restaurant.Restaurant result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.location_ = location_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.contactNumber_ = contactNumber_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.grpc.restaurant.Restaurant) {
        return mergeFrom((me.grpc.restaurant.Restaurant)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.grpc.restaurant.Restaurant other) {
      if (other == me.grpc.restaurant.Restaurant.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLocation().isEmpty()) {
        location_ = other.location_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getContactNumber().isEmpty()) {
        contactNumber_ = other.contactNumber_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (menuBuilder_ == null) {
        if (!other.menu_.isEmpty()) {
          if (menu_.isEmpty()) {
            menu_ = other.menu_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMenuIsMutable();
            menu_.addAll(other.menu_);
          }
          onChanged();
        }
      } else {
        if (!other.menu_.isEmpty()) {
          if (menuBuilder_.isEmpty()) {
            menuBuilder_.dispose();
            menuBuilder_ = null;
            menu_ = other.menu_;
            bitField0_ = (bitField0_ & ~0x00000008);
            menuBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMenuFieldBuilder() : null;
          } else {
            menuBuilder_.addAllMessages(other.menu_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              location_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              contactNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              me.grpc.restaurant.MenuItem m =
                  input.readMessage(
                      me.grpc.restaurant.MenuItem.parser(),
                      extensionRegistry);
              if (menuBuilder_ == null) {
                ensureMenuIsMutable();
                menu_.add(m);
              } else {
                menuBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object location_ = "";
    /**
     * <code>string location = 2;</code>
     * @return The location.
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location = 2;</code>
     * @return The bytes for location.
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location = 2;</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      location_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string location = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      location_ = getDefaultInstance().getLocation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string location = 2;</code>
     * @param value The bytes for location to set.
     * @return This builder for chaining.
     */
    public Builder setLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      location_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object contactNumber_ = "";
    /**
     * <code>string contact_number = 3;</code>
     * @return The contactNumber.
     */
    public java.lang.String getContactNumber() {
      java.lang.Object ref = contactNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contact_number = 3;</code>
     * @return The bytes for contactNumber.
     */
    public com.google.protobuf.ByteString
        getContactNumberBytes() {
      java.lang.Object ref = contactNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contact_number = 3;</code>
     * @param value The contactNumber to set.
     * @return This builder for chaining.
     */
    public Builder setContactNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contactNumber_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string contact_number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContactNumber() {
      contactNumber_ = getDefaultInstance().getContactNumber();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string contact_number = 3;</code>
     * @param value The bytes for contactNumber to set.
     * @return This builder for chaining.
     */
    public Builder setContactNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contactNumber_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<me.grpc.restaurant.MenuItem> menu_ =
      java.util.Collections.emptyList();
    private void ensureMenuIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        menu_ = new java.util.ArrayList<me.grpc.restaurant.MenuItem>(menu_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        me.grpc.restaurant.MenuItem, me.grpc.restaurant.MenuItem.Builder, me.grpc.restaurant.MenuItemOrBuilder> menuBuilder_;

    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public java.util.List<me.grpc.restaurant.MenuItem> getMenuList() {
      if (menuBuilder_ == null) {
        return java.util.Collections.unmodifiableList(menu_);
      } else {
        return menuBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public int getMenuCount() {
      if (menuBuilder_ == null) {
        return menu_.size();
      } else {
        return menuBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public me.grpc.restaurant.MenuItem getMenu(int index) {
      if (menuBuilder_ == null) {
        return menu_.get(index);
      } else {
        return menuBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder setMenu(
        int index, me.grpc.restaurant.MenuItem value) {
      if (menuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuIsMutable();
        menu_.set(index, value);
        onChanged();
      } else {
        menuBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder setMenu(
        int index, me.grpc.restaurant.MenuItem.Builder builderForValue) {
      if (menuBuilder_ == null) {
        ensureMenuIsMutable();
        menu_.set(index, builderForValue.build());
        onChanged();
      } else {
        menuBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder addMenu(me.grpc.restaurant.MenuItem value) {
      if (menuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuIsMutable();
        menu_.add(value);
        onChanged();
      } else {
        menuBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder addMenu(
        int index, me.grpc.restaurant.MenuItem value) {
      if (menuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuIsMutable();
        menu_.add(index, value);
        onChanged();
      } else {
        menuBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder addMenu(
        me.grpc.restaurant.MenuItem.Builder builderForValue) {
      if (menuBuilder_ == null) {
        ensureMenuIsMutable();
        menu_.add(builderForValue.build());
        onChanged();
      } else {
        menuBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder addMenu(
        int index, me.grpc.restaurant.MenuItem.Builder builderForValue) {
      if (menuBuilder_ == null) {
        ensureMenuIsMutable();
        menu_.add(index, builderForValue.build());
        onChanged();
      } else {
        menuBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder addAllMenu(
        java.lang.Iterable<? extends me.grpc.restaurant.MenuItem> values) {
      if (menuBuilder_ == null) {
        ensureMenuIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, menu_);
        onChanged();
      } else {
        menuBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder clearMenu() {
      if (menuBuilder_ == null) {
        menu_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        menuBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public Builder removeMenu(int index) {
      if (menuBuilder_ == null) {
        ensureMenuIsMutable();
        menu_.remove(index);
        onChanged();
      } else {
        menuBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public me.grpc.restaurant.MenuItem.Builder getMenuBuilder(
        int index) {
      return getMenuFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public me.grpc.restaurant.MenuItemOrBuilder getMenuOrBuilder(
        int index) {
      if (menuBuilder_ == null) {
        return menu_.get(index);  } else {
        return menuBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public java.util.List<? extends me.grpc.restaurant.MenuItemOrBuilder> 
         getMenuOrBuilderList() {
      if (menuBuilder_ != null) {
        return menuBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(menu_);
      }
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public me.grpc.restaurant.MenuItem.Builder addMenuBuilder() {
      return getMenuFieldBuilder().addBuilder(
          me.grpc.restaurant.MenuItem.getDefaultInstance());
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public me.grpc.restaurant.MenuItem.Builder addMenuBuilder(
        int index) {
      return getMenuFieldBuilder().addBuilder(
          index, me.grpc.restaurant.MenuItem.getDefaultInstance());
    }
    /**
     * <code>repeated .MenuItem menu = 4;</code>
     */
    public java.util.List<me.grpc.restaurant.MenuItem.Builder> 
         getMenuBuilderList() {
      return getMenuFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        me.grpc.restaurant.MenuItem, me.grpc.restaurant.MenuItem.Builder, me.grpc.restaurant.MenuItemOrBuilder> 
        getMenuFieldBuilder() {
      if (menuBuilder_ == null) {
        menuBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            me.grpc.restaurant.MenuItem, me.grpc.restaurant.MenuItem.Builder, me.grpc.restaurant.MenuItemOrBuilder>(
                menu_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        menu_ = null;
      }
      return menuBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Restaurant)
  }

  // @@protoc_insertion_point(class_scope:Restaurant)
  private static final me.grpc.restaurant.Restaurant DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.grpc.restaurant.Restaurant();
  }

  public static me.grpc.restaurant.Restaurant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Restaurant>
      PARSER = new com.google.protobuf.AbstractParser<Restaurant>() {
    @java.lang.Override
    public Restaurant parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Restaurant> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Restaurant> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.grpc.restaurant.Restaurant getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

