// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: restaurant.proto
// Protobuf Java Version: 4.28.2

package me.grpc;

public interface MenuItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MenuItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>float price = 3;</code>
   * @return The price.
   */
  float getPrice();

  /**
   * <pre>
   * category of the menu item (using the Category enum)
   * </pre>
   *
   * <code>.Category category = 4;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <pre>
   * category of the menu item (using the Category enum)
   * </pre>
   *
   * <code>.Category category = 4;</code>
   * @return The category.
   */
  me.grpc.Category getCategory();

  /**
   * <code>bool available = 5;</code>
   * @return The available.
   */
  boolean getAvailable();
}
