// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: restaurant.proto
// Protobuf Java Version: 4.28.2

package me.grpc;

public final class RestaurantOuterClass {
  private RestaurantOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      RestaurantOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MenuItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MenuItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Restaurant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Restaurant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RestaurantList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RestaurantList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MenuItemList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MenuItemList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020restaurant.proto\"l\n\010MenuItem\022\014\n\004name\030\001" +
      " \001(\t\022\023\n\013description\030\002 \001(\t\022\r\n\005price\030\003 \001(\002" +
      "\022\033\n\010category\030\004 \001(\0162\t.Category\022\021\n\tavailab" +
      "le\030\005 \001(\010\"]\n\nRestaurant\022\014\n\004name\030\001 \001(\t\022\020\n\010" +
      "location\030\002 \001(\t\022\026\n\016contact_number\030\003 \001(\t\022\027" +
      "\n\004menu\030\004 \003(\0132\t.MenuItem\"2\n\016RestaurantLis" +
      "t\022 \n\013restaurants\030\001 \003(\0132\013.Restaurant\"\007\n\005E" +
      "mpty\"\033\n\013NameRequest\022\014\n\004name\030\001 \001(\t\".\n\017Cat" +
      "egoryRequest\022\033\n\010category\030\001 \001(\0162\t.Categor" +
      "y\"(\n\014MenuItemList\022\030\n\005items\030\001 \003(\0132\t.MenuI" +
      "tem\",\n\010Response\022\017\n\007success\030\001 \001(\010\022\017\n\007mess" +
      "age\030\002 \001(\t*a\n\010Category\022\013\n\007UNKNOWN\020\000\022\r\n\tAP" +
      "PETIZER\020\001\022\017\n\013MAIN_COURSE\020\002\022\013\n\007DESSERT\020\003\022" +
      "\014\n\010BEVERAGE\020\004\022\r\n\tSIDE_DISH\020\0052\327\001\n\021Restaur" +
      "antService\022\'\n\rAddRestaurant\022\013.Restaurant" +
      "\032\t.Response\022,\n\021GetAllRestaurants\022\006.Empty" +
      "\032\017.RestaurantList\0220\n\023GetRestaurantByName" +
      "\022\014.NameRequest\032\013.Restaurant\0229\n\026GetMenuIt" +
      "emsByCategory\022\020.CategoryRequest\032\r.MenuIt" +
      "emListB\013\n\007me.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MenuItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MenuItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MenuItem_descriptor,
        new java.lang.String[] { "Name", "Description", "Price", "Category", "Available", });
    internal_static_Restaurant_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Restaurant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Restaurant_descriptor,
        new java.lang.String[] { "Name", "Location", "ContactNumber", "Menu", });
    internal_static_RestaurantList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RestaurantList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RestaurantList_descriptor,
        new java.lang.String[] { "Restaurants", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_NameRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_NameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NameRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_CategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CategoryRequest_descriptor,
        new java.lang.String[] { "Category", });
    internal_static_MenuItemList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_MenuItemList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MenuItemList_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Success", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
